### ISSUE TITLE
SUGGESTION

### ISSUE THREAD

**Issue by twist84** [FishPhd/FishPlayer#1]
If a song doesn't have a contributing artists can you make it use Album artists.

**Comment by FishPhd** [comment]
Where are you seeing contributing artist? The list only pulls artists names which would be the most common metadata for a song to have.

**Comment by twist84** [comment]
https://blam.halo.click/nZai9T.png

Most of my music collection only has contributing artists instead of album artists

**Comment by FishPhd** [comment]
Oh I see, you wrote your issue backwards. I'm redoing metadata loading soon so I'll be sure to throw in all the artist info into one.

**Comment by twist84** [comment]
Oh yeah so I did sorry about that and thanks for taking the time.

**Comment by FishPhd** [comment]
Fixed in 3f0a608ceef12874da53344f9ea6693c254b50b3
