### ISSUE TITLE
Exit maximized mode with window drag

### ISSUE THREAD

**Issue by Delivator** [FishPhd/FishPlayer#18]
When you set the programm to maximized (with the " Expand Player"button in the top left corner), and again to normal (with dragging the window on title bar or pressing WIN+ARROW-DOWN) the whole overlay is a little bit buggy, and you have to press the "Shrik Player" button.
![animation](https://cloud.githubusercontent.com/assets/11231245/17373222/89437854-59a7-11e6-91ab-62a34dafbcd5.gif)
(This gif was made afer i dragged the window down)

**Comment by FishPhd** [comment]
Interesting I thought I disabled resizing. You are changing the size of the window by dragging at the edge correct? (or to that effect)

**Comment by Delivator** [comment]
No, resizing is disabled. I pressed the "Expand Player" (Top left "+") button, set the window to Maximized, and left the Maximized state not with pressing the "Shrink Player" button, but with dragging the window down, or with pressing Windows-Key + Arrow Down.

**Comment by FishPhd** [comment]
Putting on hold since i removed whale mode temporarily
